version: '{build}'

environment:
  irrklang_pro:
    secure: IHiumvV9+f+4JOGb9Al3Husl+Hox2gCq90R74mJQy+g=

install:
  # environment and system dependency
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-windows.zip ; exit 0"
  - 7z x premake-5.0.0-alpha12-windows.zip
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz ; exit 0"
  - tar xf libevent-2.0.22-stable.tar.gz
  - move libevent-2.0.22-stable event
  - xcopy /E event\WIN32-Code event\include
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name http://downloads.sourceforge.net/freetype/freetype-2.8.tar.bz2 ; exit 0"
  - tar xf freetype-2.8.tar.bz2
  - move freetype-2.8 freetype
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name http://downloads.sourceforge.net/irrlicht/irrlicht-1.8.4.zip ; exit 0"
  - 7z x irrlicht-1.8.4.zip
  - md irrlicht
  - move irrlicht-1.8.4\source\Irrlicht irrlicht\src
  - move irrlicht-1.8.4\include irrlicht\include
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.lua.org/ftp/lua-5.3.4.tar.gz ; exit 0"
  - tar xf lua-5.3.4.tar.gz
  - move lua-5.3.4\src lua
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.sqlite.org/2017/sqlite-amalgamation-3200100.zip ; exit 0"
  - 7z x sqlite-amalgamation-3200100.zip
  - move sqlite-amalgamation-3200100 sqlite3
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name http://www.ambiera.at/downloads/irrKlang-32bit-1.5.0.zip ; exit 0"
  - 7z x irrKlang-32bit-1.5.0.zip
  - move irrKlang-1.5.0 irrklang
  - move irrklang\plugins\ikpMP3 ikpmp3

  # let premake happy
  - xcopy /E premake\* .

  #irrklang pro
  - rm -rf irrklang/lib/Win32-visualStudio/irrKlang.lib
  - 7z x -oirrklang/lib/Win32-visualStudio -p%irrklang_pro% irrKlang.7z
  
  # patch irrlicht and ikpmp3
  - patch -p0 < irrlicht\irrlicht.patch
  - patch -p0 < ikpmp3\ikpmp3.patch

  # premake
  - premake5 vs2015
  
configuration: Release

build: 
    project: build/ygo.sln
    parallel: true

after_build:
  - mv bin\release\ygopro.exe ygopro_thc.exe

test: off

artifacts:
  - path: ygopro_thc.exe
    name: ygopro_thc

cache:
  - premake-5.0.0-alpha12-windows.zip
  - libevent-2.0.22-stable.tar.gz
  - freetype-2.8.tar.bz2
  - irrlicht-1.8.4.zip
  - lua-5.3.4.tar.gz
  - sqlite-amalgamation-3200100.zip
  - irrKlang-32bit-1.5.0.zip
  - sqlite-amalgamation-3150200.zip
  - premake-5.0.0-alpha10-windows.zip
  - Redis-x64-3.2.100.zip
