version: '{build}'
skip_tags: true

install:
 - git config --global user.name "Smile-DK"
 - git config --global user.email "2236141431@qq.com"
 - git pull origin data
 - mkdir temp
 - cp -rf expansions temp
 - rm -rf temp/expansions/pics
 - cp -rf lflist.conf temp
 - git clone https://github.com/purerosefallen/ygopro-7210srv
 - cp -rf ygopro-7210srv/cards.cdb temp
 - cp -rf ygopro-7210srv/strings.conf temp
 - rm -rf ygopro-7210srv
 - git checkout master
 - git pull origin master
 - cp -rf temp/* .
 - rm -rf temp

build:
 script:
 - git add . -A
 - git commit -m "Push by Appveyor"
 - git tag NoBuild HEAD
 - git push %Smile%purerosefallen/ygopro-222DIY master

after_build:

test: off