version: '{build}'

install:
  - git submodule update --init --recursive

  # environment and system dependency
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-windows.zip ; exit 0"
  - 7z x premake-5.0.0-alpha10-windows.zip
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz ; exit 0"
  - tar xf libevent-2.0.22-stable.tar.gz
  - move libevent-2.0.22-stable event
  - xcopy /E event\WIN32-Code event\include
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.lua.org/ftp/lua-5.2.4.tar.gz ; exit 0"
  - tar xf lua-5.2.4.tar.gz
  - move lua-5.2.4\src lua
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.sqlite.org/2016/sqlite-amalgamation-3150200.zip ; exit 0"
  - 7z x sqlite-amalgamation-3150200.zip
  - move sqlite-amalgamation-3150200 sqlite3
  
  - appveyor DownloadFile https://github.com/tronkko/dirent/raw/master/include/dirent.h
  - move dirent.h gframe\

  # let premake happy
  - xcopy /E premake\* .
  
  # premake
  - premake5 vs2015
  
configuration: Release

build: 
    project: build/ygo.sln
    parallel: true

after_build:
  - ps: move bin\release\ygopro.exe .
  - git config --global user.name "Smile-DK"
  - git config --global user.email "2236141431@qq.com"
  - git clone https://github.com/Smile-DK/ygopro-svrelease
  - cd ygopro-svrelease
  - rm -rf 222
  - mkdir 222
  - cp -rf ../ygopro.exe 222
  - git add . -A
  - git commit -m "Push by Appveyor"
  - git push %Smile%Smile-DK/ygopro-svrelease master
  - cd ..
  - git clone https://github.com/purerosefallen/ygopro-7210srv
  - git clone https://github.com/moecube/ygopro-server
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://npm.taobao.org/mirrors/node/v8.4.0/node-v8.4.0-win-x64.zip ; exit 0"
  - cd ygopro-server
  - cp -rf ../start.bat .
  - mkdir ygopro
  - cd ygopro
  - git clone https://github.com/Fluorohydride/ygopro-scripts script
  - mkdir replay
  - cp -rf ../../expansions .
  - cp -rf ../../ygopro-7210srv/expansions .
  - cp -rf ../../gframe .
  - cp -rf ../../ocgcore .
  - cp -rf ../../ygopro-7210srv/premake .
  - cp -rf ../../ygopro-7210srv/cards.cdb .
  - cp -rf ../../ygopro-7210srv/textures .
  - cp -rf ../../ygopro-7210srv/*.lua .
  - cp -rf ../../lflist.conf .
  - cp -rf ../../ygopro-7210srv/strings.conf .
  - cp -rf ../../ygopro-7210srv/system.conf .
  - cp -rf ../../ygopro.exe .
  - cd ..
  - cp -rf ../node-v8.4.0-win-x64.zip .
  - 7z x node-v8.4.0-win-x64.zip
  - rm -rf node-v8.4.0-win-x64.zip
  - cp -rf node-v8.4.0-win-x64/* .
  - rm -rf node-v8.4.0-win-x64
  - npm install
  - npm install pm2@latest -g
  - npm install ws
  - npm install redis
  - cd ..
  - 7z a ygopro-222DIY-server.7z ygopro-server -mx=9 -xr!.git*
test: off

artifacts:
  - path: ygopro.exe
    name: ygopro
  - path: ygopro-222DIY-server.7z
    name: ygopro-222DIY-server	

cache:
  - premake-5.0.0-alpha10-windows.zip
  - libevent-2.0.22-stable.tar.gz
  - lua-5.2.4.tar.gz
  - sqlite-amalgamation-3150200.zip
  - node-v8.4.0-win-x64.zip
branches:
  only:
  - master
